### ISSUE TITLE
TS: ws folders are not considered if one of them has no tsconfig.json

### ISSUE THREAD

**Issue by moepmoep12** [iljapostnovs/ui5plugin-parser#59]
Consider the following folder structure

![image](https://user-images.githubusercontent.com/32679211/210570679-445c38fa-2f45-477b-b824-5f2409fa484e.png)

where root does not have a tsconfig.json. When the root folder is part of a multi-root workspace, e.g.

`{ "folders": [ { "name": "root", "path": "." }, { "name": "server", "path": "/packages/server" }, { "name": "app", "path": "/packages/app" } ], }`,

the following [line](https://github.com/iljapostnovs/ui5plugin-parser/blob/master/src/UI5TSParser.ts#L82)  will throw the error, that root does not contain a tsconfig.json and thus the other ws folders will not be processed.

I propose adding a try catch [here](https://github.com/iljapostnovs/ui5plugin-parser/blob/master/src/UI5TSParser.ts#L59) such that invalid projects are skipped.

**Comment by iljapostnovs** [comment]
Also it's released in VSCode extension, v0.15.5

**Comment by iljapostnovs** [comment]
@moepmoep12, I will assume that everything works and close the issue.
Please either contact me here or create new issue if problem is not solved.
