### ISSUE TITLE
XML linter does not recognize parameters of an event handler correctly

### ISSUE THREAD

**Issue by richardatsap** [iljapostnovs/ui5plugin-parser#61]
**Describe the bug**
The xml linter complains if parameters of an event handler are the result of another function call. See screenshot.
This is allowed syntax for event handlers, see https://sapui5.hana.ondemand.com/#/topic/b0fb4de7364f4bcbb053a99aa645affe. 

**To Reproduce**
Any event handler having a function call as parameter shows this behavior. Culprit seems to be the opening bracket which seems to throw the parser off.

**Screenshots**
![image](https://user-images.githubusercontent.com/3874348/214568172-4a700bd7-5c16-4454-a642-c8c86e1cd174.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by iljapostnovs** [comment]
Hi!

Thanks for another bug report :)
Fixed via v0.15.5 of VSCode extension, please check if it works for you now.

**Comment by richardatsap** [comment]
Hi!

thanks for the quick fix! Works now, if the arguments are on the same line.

Because of the long argument list I put the parameters on separate lines (no problem for UI5) and the linter complains again.

See:
![image](https://user-images.githubusercontent.com/3874348/214775139-7b8d0707-30ec-41ad-a965-45dc9d750f6f.png)

**Comment by iljapostnovs** [comment]
Hi, please check VSCode extension v0.15.6

**Comment by richardatsap** [comment]
Hi,

thanks, works like a charm.
