### ISSUE TITLE
FileReader getManifestForClass returns wrong manifest in multiproject workspace

### ISSUE THREAD

**Issue by unlogik** [iljapostnovs/ui5plugin-parser#68]
**Description**
In multiproject workspace in some cases navigation between controller and view by F3 is not working. It happens when component id from one project is prefix of other project's component id. For example one component id is ui5.project and the other is ui5.project.main.

**To Reproduce**
1. Create workspace folder
2. Create two projects in workspace folder
3. Set id of first project (A) and component id  to ui5.project
4. Set id of second project (B) and component id to ui5.project.main
5. Create view with controller in project (B)
6. Open view in editor and try switching to controller by F3

**Expected behavior**
It is not navigating to controller. Navigation from controller to view is working but not from view to controller.

**Desktop (please complete the following information):**
 - Detected on Mac OS

**Additional context**
Problem is in the method getManifestForClass of FileReader. It is getting manifest by id that class name begins with. Problem is that we have two manifest entries that matches and it is taking the first one. 

Example this._manifests:
[ {componeName = ui5.project,....}
   componeName = ui5.project.main,....}]
For className ui5.project.main.Super.controller.js it is searching className.startsWith(UIManifest.componentName) and returns the first one.

Correct approach would be to get the longest match. I tried sorting array of manifests by length of component id so longest goes first and it solved the issue. Not sure if this is correct approach as manifest list is also used elsewhere. 

If you do not mind I would like to participate in solving the issue.

**Comment by iljapostnovs** [comment]
Sorry that I didn't accept your PR, I was working on v1.0.0 release and it didn't fit anymore into new code base

**Comment by unlogik** [comment]
No problem. I see there are a lot of changes you made and my fix does not fit any more. Hope I can help in the future.
Thanks for providing such a great tool!
