### ISSUE TITLE
excludeFolderPatterns not working after update to version 1.5.1

### ISSUE THREAD

**Issue by bschraml** [iljapostnovs/ui5plugin-parser#88]
Hello,

after update to version 1.5.1 it seems to be that the "excludeFolderPatterns" setting in the package.json does'nt work anymore.
I got the warning message in VSCode "Initialization warnings: Multiple manifests with same app id found: ...".

package.json

`"ui5parser": {
    "excludeFolderPatterns": ["**/dist/**", "**/out/**", "**/node_modules/**"]
  }`

**Comment by iljapostnovs** [comment]
Hi,

Thanks for bug report.
Did you get this bug in VSCode extension or using the `ui5plugin-lintrer`?

**Comment by bschraml** [comment]
> Hi,
> 
> Thanks for bug report. Did you get this bug in VSCode extension or using the `ui5plugin-lintrer`?

In the VSCode extension (SAPUI5 Extension version 1.8.0)

**Comment by iljapostnovs** [comment]
Please try now

**Comment by bschraml** [comment]
Now it works fine :-)

Thanks for the quick fix Ilja!

Cheers,
Benny
