### ISSUE TITLE
Proxy workspaces in VSCode workspace

### ISSUE THREAD

**Issue by moepmoep12** [iljapostnovs/ui5plugin-parser#92]
**Describe the bug**
Infinite recursion when using proxy workspaces in a project opened as a VSCode multi-root workspace.

**To Reproduce**
Consider the CAP project described in the README:

```
├── frontend
│   ├── webapp
│   │   └── manifest.json
│   ├── package.json (<- this file will be used as configuration source after proxyWorkspaces is configured)
│   └── tsconfig.json
├── backend
│   ├── Whatever.js
│   └── package.json
├── package.json (<- proxyWorkspaces should be configured here)
└── tsconfig.json
```

And the entry in the root package.json as described in the README:

```
"ui5": {
   "ui5parser": {
      "proxyWorkspaces" : ["./frontend"]
   }
}
```

And the VSCode .workspace:

```
{
  "folders": [
    {
      "name": "root",
      "path": ".."
    },
    {
      "name": "backend",
      "path": "./backend"
    },
    {
      "name": "frontend",
      "path": "./frontend"
    }
  ]
}
```

**Expected behavior**
Loading to halt.

**Additional context**
The infinite recursion occurs in the method `_extractAllWSFoldersAndConfigHandlers` of ParserFactory. Here, the frontend ws is never discarded. Hence, the recursion never ends.

**Comment by iljapostnovs** [comment]
Hi.
1) Please provide the project example in order to reproduce the issue.
2) I don't really get the idea of your configuration. You have MultiWorkspace setup with `root` folder, which includes `backend` and `frontend`, and then `backend` and `frontend` folder added to the same MultiWorkspace again?

**Comment by moepmoep12** [comment]
Hi,

I have uploaded an example project: https://github.com/moepmoep12/ui5-plugin-cap-example.

> I don't really get the idea of your configuration. You have MultiWorkspace setup with root folder, which includes backend and frontend, and then backend and frontend folder added to the same MultiWorkspace again?

Yes, but the backend & frontend folders are inside a `/packages` folder because there might be more apps.

**Comment by iljapostnovs** [comment]
Please check now

**Comment by moepmoep12** [comment]
It works, thank you.

**Comment by iljapostnovs** [comment]
> It works, thank you.

Thanks for the bug report!
